In [2]:
import numpy as np
import math

In [27]:
rotor_length = 400 - 15
rotor_depth = 45.5

rotor_volume =  23679.529297 / 1000000000
rotor_cog = np.array([18.839804, 0.537746, 200.827209])

rotor_density = 1250
rotor_mass = rotor_density * rotor_volume

rod_diameter = 2
rod_length = 400
rod_volume = rod_length * math.pi*(rod_diameter/2)**2 / 1000000000
rod_density = 8500
rod_density = 19300
rod_cog = np.array([3.4, 0.3, rod_length/2])
rod_mass = rod_density * rod_volume

rod2_diameter = 0
rod2_length = 400
rod2_volume = rod2_length * math.pi*(rod2_diameter/2)**2 / 1000000000
rod2_density = 8500
rod2_cog = np.array([rotor_depth/4 - 3.5, 0, rod2_length/2])
rod2_mass = rod2_density * rod2_volume

rod3_diameter = 1
rod3_length = 400
rod3_volume = rod3_length * math.pi*(rod3_diameter/2)**2 / 1000000000
rod3_density = 2270
rod3_cog = np.array([rotor_depth/4 + 3.5, 0, rod3_length/2])
rod3_mass = rod3_density * rod3_volume


print("Teziste rotoru bez vyztuhy", rotor_cog)
print("Hmotnost rotoru:", rotor_mass*1000, "g")
print("Teziste vyztuhy 1:", rod_cog)
print("Hmotnost vyztuhy 1:", rod_mass*1000, "g")
print("Teziste vyztuhy 2:", rod2_cog)
print("Hmotnost vyztuhy 2:", rod2_mass*1000, "g")

print("Celkova hmotnost: ", (rotor_mass + rod_mass + rod2_mass) *1000)

Teziste rotoru bez vyztuhy [  18.839804    0.537746  200.827209]
Hmotnost rotoru: 29.599411621250002 g
Teziste vyztuhy 1: [   3.4    0.3  200. ]
Hmotnost vyztuhy 1: 24.253095285713204 g
Teziste vyztuhy 2: [   7.875    0.     200.   ]
Hmotnost vyztuhy 2: 0.0 g
Celkova hmotnost:  53.85250690696321


In [28]:
new_cog = ((rod3_mass * rod3_cog)+(rod2_mass * rod2_cog)+(rod_mass * rod_cog)+(rotor_mass * rotor_cog))/(rod_mass + rotor_mass + rod2_mass + rod3_mass)

In [29]:
print("Idealni X pozice: ", rotor_depth/4)
print("Celkove teziste:", new_cog)

Idealni X pozice:  11.375
Celkove teziste: [  11.9253713     0.42504569  200.4487237 ]


In [2]:
import json
import math
import numpy as np
np.set_printoptions(suppress=True)

In [14]:
slicing = json.load(open('../CAD/src/gcode/111_1009.json'))
print(slicing)

{'cog': {'X': 92.47254015041118, 'Y': 100.58382102188283, 'Z': 201.5605660740305}, 'file': '111_1009.gcode', 'slicer_translation': {'X': 78.0, 'Y': 99.0, 'Z': 0.0}, 'stl_cog': {'X': 14.472540150411177, 'Y': 1.5838210218828266, 'Z': 201.5605660740305}}


In [83]:
slicing = {'cog': {'gcode': {'X': 88.62054190023312, 'Y': 98.05033551818555, 'Z': 203.39622894600623}, 'model': {'X': 11.620541900233121, 'Y': -0.9496644818144517, 'Z': 203.39622894600623}, 'slicer_translation': {'X': 77.0, 'Y': 99.0, 'Z': 0.0}, 'model_method': None}, 'material': {'extrudate': 4510.432899999963, 'volume': 7.0685834705770345, 'mass': 0.0}}
slicing = {'cog': {'gcode': {'X': 87.28694932256897, 'Y': 98.24747423940666, 'Z': 200.14500111760856}, 'model': {'X': 11.286949322568972, 'Y': -0.7525257605933433, 'Z': 200.14500111760856}, 'slicer_translation': {'X': 76.0, 'Y': 99.0, 'Z': 0.0}, 'model_method': None}, 'material': {'extrudate': 5209.028030000088, 'volume': 7.0685834705770345, 'mass': 0.0}}


depth = 50
print(slicing['cog']['model'], depth/4)

{'X': 11.286949322568972, 'Y': -0.7525257605933433, 'Z': 200.14500111760856} 12.5


In [84]:
slicing['material']['mass'] = 1.24 * slicing['material']['volume']*10

print(math.pi * 1.75**2 * slicing['material']['extrudate'])

x1 = np.array([slicing['cog']['model']['X'], slicing['cog']['model']['Y'], slicing['cog']['model']['Z']])
m1 = slicing['material']['mass']

# Mosazna
x2 = np.array([45.5/4 - 3, 0, slicing['cog']['model']['Z']])
m2 = 0.4 * 24.1

# Uhlikoav
x3 = np.array([45.5/4 + 3, 0, slicing['cog']['model']['Z']])
m3 = 0.4 * 4.9

cog = (x1*m1) + (x2*m2) + (x3*m3)
cog /= (m1+m2+m3)

target = np.array([depth/4, 0, 0])

print(x1, m1)
print(x2, m2)
print(x3, m3)

print(cog, m1+m2)

print(cog-target)

50116.72283613674
[ 11.28694932  -0.75252576 200.14500112] 87.65043503515523
[  8.375        0.         200.14500112] 9.64
[ 14.375        0.         200.14500112] 1.9600000000000002
[ 11.0651003   -0.66457351 200.14500112] 97.29043503515523
[ -1.4348997   -0.66457351 200.14500112]
